spring:
  application:
    name: petflower
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

springdoc.swagger-ui.path: /swagger-ui

jwt:
  access:
    lifetime: ${ACCESS_LIFETIME_MINUTES}
    secret: ${JWT_ACCESS}
  refresh:
    lifetime: ${REFRESH_LIFETIME_DAYS}
    secret: ${JWT_REFRESH}

measures:
  deviation: ${MEASURES_DEVIATION}