spring:
  application:
    name: petflower
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

springdoc.swagger-ui.path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml

jwt:
  access:
    lifetime: ${ACCESS_LIFETIME_MINUTES}
    secret: ${JWT_ACCESS}
  refresh:
    lifetime: ${REFRESH_LIFETIME_DAYS}
    secret: ${JWT_REFRESH}

measures:
  deviation: ${MEASURES_DEVIATION}
  battery:
    max: ${BATTERY_MAX:2000}
    min: ${BATTERY_MIN:1600}
  moisture:
    max: ${MOISTURE_MAX:1000}
    min: ${MOISTURE_MIN:2400}
